In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
obs_size=24
action_size=4
table=np.zeros(obs_size,action_size)
table.shape()

In [ ]:
obs_size=24
action_size=4
def Q_learn():
    # observation space is 24, action is 4, assume state is equal to obs
    Q_table= np.zeros(obs_size,action_size)


In [ ]:
import gym
#LunarLander-v2
#python gym/envs/box2d/bipedal_walker.py
#BipedalWalker-v3
#CartPole-v1
env = gym.make("BipedalWalker-v3",render_mode="human")
observation, info = env.reset(seed=42, return_info=True)

for _ in range(1000):

    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print(action)
    if done:
        observation, info = env.reset(return_info=True)
env.close()
print(reward)

In [ ]:
print(env.action_space.shape ,observation.size)

In [ ]:
#print(observation)
print(reward)



In [ ]:
observation

In [2]:
#print(observation)
print(reward)



-0.07604836109280587


In [3]:
observation

array([ 6.2141348e-02, -4.9744127e-03, -2.5972214e-02,  1.9911097e-02,
       -7.3044628e-01,  1.2499954e-01, -6.2816501e-01, -9.9998897e-01,
        0.0000000e+00,  1.1082498e+00,  7.1525574e-07,  9.3490732e-01,
        1.5737464e-03,  1.0000000e+00,  2.2973527e-01,  2.3234425e-01,
        2.4047576e-01,  2.5513467e-01,  2.7835375e-01,  3.1397945e-01,
        3.6958104e-01,  4.6171349e-01,  6.3400126e-01,  1.0000000e+00],
      dtype=float32)

In [4]:
for i in range(40):
    print(env.action_space.sample())

[ 0.17722179 -0.81600684 -0.57724774 -0.05013111]
[-0.4571788   0.7102515  -0.2385167  -0.45787433]
[-0.90532774  0.69443667  0.4218248  -0.49344227]
[-0.8082145  -0.27561927  0.5454736  -0.17809473]
[ 0.87434584  0.7635797  -0.2186255  -0.49479973]
[-0.8421861  0.2143691  0.3033633 -0.389969 ]
[-0.5042189   0.24916908  0.4685806   0.13646188]
[ 0.6292686   0.7172533   0.11109225 -0.74738806]
[-0.22080334 -0.63543665 -0.37682873  0.24175404]
[ 0.76789963  0.46594495 -0.14329144  0.3920047 ]
[-0.5904866  -0.18356302  0.03182431 -0.5538152 ]
[-0.03460261  0.3026079   0.04255234  0.46719337]
[-0.22694883  0.9696545   0.7357894   0.6797835 ]
[-0.24364486 -0.42422003  0.53626925  0.04267367]
[ 0.17905734  0.93494403 -0.47969225  0.762298  ]
[-0.97717613 -0.64158106 -0.8060654  -0.02709807]
[-0.714797   -0.7613223   0.4119543  -0.68601775]
[-0.8400358  -0.95874286 -0.9812047   0.1270022 ]
[-0.2713477   0.88510346 -0.101604   -0.6460893 ]
[-0.98662335  0.7918652   0.13846312  0.50113285]
[ 0.

NameError: name 'impo' is not defined

In [ ]:
import